### ISSUE TITLE
Swipe to go back - iOS

### ISSUE THREAD

**Issue by Pimsch** [AlexandrNikulin/AnimationNavigationPage#1]
Hello,
i am running into an issue on iOS devices where the "Swipe to go back" gesture only works once when using your AnimationNavigationPage. After that the gesture is not recognized anymore.

**Comment by AlexandrNikulin** [comment]
@Pimsch 
True, for now "Swipe to go back" not supported.
It will be implement in version 1.2.1

**Comment by AlexandrNikulin** [comment]
@Pimsch 
Implemented in version 1.2.1
