### ISSUE TITLE
iOS Title bar is included in the animation

### ISSUE THREAD

**Issue by ant81584** [AlexandrNikulin/AnimationNavigationPage#11]
On iOS, it is strange how the title bar is included in the animation. It looks like on Android it does not have this issue.

Is that something that is configurable?

**Comment by AlexandrNikulin** [comment]
@ant81584 
-> Is that something that is configurable?
Unfortunately not. On iOS navigation bar is included in the animation. This is standard behavior for iOS.

**Comment by AlexandrNikulin** [comment]
@ant81584  i find solution for this. We will have property for configure this behavior for iOS.
Please contact with me - i will send test lib with this property.

**Comment by AlexandrNikulin** [comment]
Implemented in ver 1.5.3
Added new property  
 public bool AnimateNavigationBar { get; set; } = true;
 in AnimationNavigationPage class.

**Comment by AlexandrNikulin** [comment]
@ant81584  ver 1.5.3 in store 
https://components.xamarin.com/view/customnavpage
