### ISSUE TITLE
Animation seems not working

### ISSUE THREAD

**Issue by mbyta** [AlexandrNikulin/AnimationNavigationPage#12]
I installed the trial version (1.5.3), XF 2.3.3.175.
I'm running the test using Microsoft android emulator.

I followed the instructions:
- in App.xaml.cs
`MainPage = new AnimationNavigationPage(new FirstPage());`

- in FirstPage.xaml.cs
```
public partial class FirstPage : ContentPage, IAnimationPage
{
   public IPageAnimation PageAnimation { get; } = new FlipPageAnimation { Duration = AnimationDuration.Long, Subtype = AnimationSubtype.FromLeft };

  //...
}
```

But when, in FirstPage, I add:

`Navigation.PushAsync(new SecondPage());`

it's still displaying the old default animation.

**Comment by AlexandrNikulin** [comment]
@mbyta  Did you init AnimationNavigationPage in iOS and Android projects ?
iOS (in AppDelegate.cs)
public override bool FinishedLaunching(UIApplication app, NSDictionary options)
    {
        Xamarin.Forms.Forms.Init();
        FormsControls.Touch.Main.Init();
        LoadApplication (new App ());
        return base.FinishedLaunching(app, options);
    }

Android: MainActivity.cs 

protected override void OnCreate(Bundle bundle)
    {
        base.OnCreate(bundle);
        Xamarin.Forms.Forms.Init(this, bundle);
        FormsControls.Droid.Main.Init(this);
        LoadApplication(new App());
    }

**Comment by AlexandrNikulin** [comment]
@mbyta  Also please notice that FlipPageAnimation not supported for AppCompatActivity (Android project, for now this animation type works only for FormsApplicationActivity). On iOS - no any limitations.
I'm working on this.

**Comment by mbyta** [comment]
OK I spotted the bug on our app. It has nothing to do with your component.

To force our app to refresh the homepage when it resumes, I added this ugly hack, because otherwise it won't call OnAppearing():
```
protected override void OnResume()
{
    // Handle when your app resumes
    Application.Current.MainPage = new NavigationPage(new MainPage());
}
```

As you may have noticed I forgot to also change this one
`new NavigationPage(new MainPage())`
to that one
`new AnimationNavigationPage(new MainPage())`

Now it works!

Thanks for your help!
