### ISSUE TITLE
Calls OnAppearing and OnDisappearing when returning to main page

### ISSUE THREAD

**Issue by JoshuaNovak919** [AlexandrNikulin/AnimationNavigationPage#13]
When you return to the main page on Android using `Navigation.PopAsync()` it calls `OnAppearing` and then `OnDisappearing` for the main page. This is causing large issues since I am registering and unregistering listeners and they are no longer working properly.

Emailed you an example project.

**Comment by AlexandrNikulin** [comment]
@JoshuaNovak919  Send last version of lib on your email.
