### ISSUE TITLE
Java.Lang.NullPointerException after Adding the References

### ISSUE THREAD

**Issue by dave2ma** [AlexandrNikulin/AnimationNavigationPage#14]
Hello Everybody, is there any experience with a Java.Lang.NullPointerException after adding the references? 
I am not sure where to store the components, maybe i do something wrong. The sample works fine and my References are almost the same in my MainProject. 

Any Help is appreciated. 

I use the 1.5.4 Version and created a components Folder on the main ProjectLevel, then I added references to the described files.  
The exception occurs irrespective of the FormsControls Inits in AppDelegate and MainActivity(which I think I did correctly). The exception seems to be caused by the base.OnCreate(bundle) in MainActivity, as I use Android for debugging. 

Thank You very much. I really would love to use this project(already paid it :D), but I am not able to :(

**Comment by dave2ma** [comment]
Okay, maybe someone's got a mistake like this, too. The thing is, for sure... that the dlls i referenced to were not included to the build. I had to involve them to a project (like a controlLibrary) and THEN CLEAN the solution ;) Sry for interrupting.

**Comment by AlexandrNikulin** [comment]
@dave2ma Hi!
If you still have problem - please update me.
