### ISSUE TITLE
On iOS, navigation bar overlaps with 2nd page when 1st page has no navigation bar

### ISSUE THREAD

**Issue by JoshaMunnik** [AlexandrNikulin/AnimationNavigationPage#17]
I've the following setup:
- 1st page has NavigationPage.HasNavigationBar="False"
- other pages shown have a NavigationBar (default setting)

On Android everything works ok. On iOS however when showing a page on top (with PushAsync) it animates correctly however the page contents is shifted up and the navigation bar overlaps with the top part.

Tested with the iOS 10.2 simulator.

**Comment by AlexandrNikulin** [comment]
Looks like a bug. I will fix it

**Comment by MuruganDurai** [comment]
Hi @AlexandrNikulin This bug is occuring in android as well. @JoshaMunnik How did you fixed this in android.

**Comment by AlexandrNikulin** [comment]
@MuruganDurai Can you create demo project with this issue ?

**Comment by MuruganDurai** [comment]
@AlexandrNikulin Working on something which needs to be completed. Will send the sample after sometime but the only difference is as it is mentioned by @JoshaMunnik 

1st page has NavigationPage.HasNavigationBar="False"
other pages shown have a NavigationBar (default setting)

**Comment by AlexandrNikulin** [comment]
@MuruganDurai  In iOS this is real bug on my implementation. But on Android i think i have not this bug. You want that i will show NavigationBar with Animation or What ?

Please check default NavigationPage. I think you will see the same behavior (on Android).

I think the best solution for your case - Hide NavPage for All pages but in that pages when you need it - create a simple Grid or other Layout that looks like NavBar. And in this case you can implement animations for this custom "NavBar" when page Appearing or Disappearing.

**Comment by AlexandrNikulin** [comment]
@MuruganDurai 

I got what the issue. But unfortunately in current implementation (Android) i can’t fix this issue.
For now i can only suggest this:
Hide NavPage for All pages but in that pages when you need it - create a simple Grid or other Layout that looks like NavBar. And in this case you can implement animations for this custom "NavBar" when page Appearing or Disappearing.

**Comment by AlexandrNikulin** [comment]
Not relevant
