### ISSUE TITLE
System.TypeInitializationException 

### ISSUE THREAD

**Issue by LeoJHarris** [AlexandrNikulin/AnimationNavigationPage#18]
Hi, I Seem to be getting this an exception after calling MainPage = new LoginPage() System.TypeInitializationException: The type initializer for 'TrackitEducationApp.Views.NavigationContentPage' threw an exception.

LoginPage extended NavigationContentPage which itself extends AnimationPage and running the latest Xamarin.forms nuget, I cant think of any other changes that might have caused this issue other then a update to xamarin forms and other respective android packages including the android.support,v4 etc.

See Screenshot for additional details and on the exception itself
![untitled](https://cloud.githubusercontent.com/assets/5468757/26186415/d90dfe1a-3be5-11e7-9dfc-11fb54653719.png)

**Comment by AlexandrNikulin** [comment]
@LeoJHarris  Hmm... Looks strange. Can you create simple demo app with this issue ?
It will help to solve problem as soon as possible.

**Comment by LeoJHarris** [comment]
Sorry I believe this issue was caused by a git command when I did a clean up of my directory as the issue happened after this event and since reverting my work the issue no longer exists and all is well again.

**Comment by AlexandrNikulin** [comment]
Nice! If you will need my help - update me.
