### ISSUE TITLE
Navbar Flicks on android

### ISSUE THREAD

**Issue by KarthickeyanSekar** [AlexandrNikulin/AnimationNavigationPage#19]
Hi @AlexandrNikulin  , 
Am using your component i had prob on Navigation . totally 3 pages in the app 1st page and the last  page have navigation bar . but  in 2nd page doesnt have a navgationbar. now , i will the animate the page small jerks on flicks on android . in ios .. running smoothly. i dnt know  its bug or not.. but give me a solution. 
Thanks..

**Comment by AlexandrNikulin** [comment]
Hi @KarthikeyanSekar93,

Can you record small video or create sample project with this issue?

I think the issue in android performance. Xamarin Forms has problem on Android with performance (and now Xamarin working on it). Try to optimize Layout on your pages.
