### ISSUE TITLE
NullReferenceException on FormsControls.Droid.Main.Init (this);

### ISSUE THREAD

**Issue by Greg767** [AlexandrNikulin/AnimationNavigationPage#20]
Hi,
This component used to work without problems and now I have an exception at startup on the line that is in the title.
What can the problem be?
Thanks

**Comment by LeoJHarris** [comment]
Im seeing the same problem to, after I upgraded from PCL to .net Standard. This needs to be fixed.

**Comment by Greg767** [comment]
The Xamarin Forms should be the latest stable and NOT the PRE! Also all the support libraries must be the ones compatible with the stable Forms release, this means 23.3.0.

**Comment by AlexandrNikulin** [comment]
@Greg767 @LeoJHarris  True, lib works only with stable Xamarin.Forms version. (Latest stable is Xamarin.Forms 2.3.4.247).

Xamarin Changed API for NavigationPage. I will support new API when new version of Xamarin.Forms will be stable.
