### ISSUE TITLE
Custom NavigationPageRenderer 

### ISSUE THREAD

**Issue by bbl-Laobu** [AlexandrNikulin/AnimationNavigationPage#21]
I am creating a custom renderer to be able to change the Back Button Style of the Navigation Bar. I've already create a repository demonstrating this at https://github.com/bbl-Laobu/CustomBackIconDemo. 

Now, I am trying to add animation to my page transitions using your solution. 
Normally, the customer renderer inherits from NavigationRenderer for iOS and  NavigationRenderer or NavigationPageRenderer (Appcomp) for Droid. 

When using your transitions solution, what should my custom renderer inherit from to still have your animations working? You can see my custom NavigationPageRenderer for iOS here https://github.com/bbl-Laobu/CustomBackIconDemo/blob/master/iOS/NavigationPageRendereriOS.cs

**Comment by AlexandrNikulin** [comment]
@bbl-Laobu  Hi! For now i'm thinking to publish all source code of my plugin.
I will update you.

**Comment by AlexandrNikulin** [comment]
@bbl-Laobu  For now you can get all source code from this repo.
