### ISSUE TITLE
.net Standard Compatibility

### ISSUE THREAD

**Issue by bbl-Laobu** [AlexandrNikulin/AnimationNavigationPage#22]
Hey,

I was wondering if your library is .net Standard compatible or if/when you were planning to do this?

Thanks,
Laobu

**Comment by AlexandrNikulin** [comment]
@bbl-Laobu Hey! Yes sure, i will support it.
For now i'm waiting stable version of Xamarin.Forms 2.3.5 (Xamarin changed internal API for NavigationPage and I'm waiting stable version for release).

**Comment by AlexandrNikulin** [comment]
@bbl-Laobu For now you can get all source code from this repo. And it will be great if you can help me with it
