### ISSUE TITLE
Page sliding alpha/transparency

### ISSUE THREAD

**Issue by LeoJHarris** [AlexandrNikulin/AnimationNavigationPage#23]
Hi again, I am using the slidepageanimation and the animation starts of transparent and loses the transparency when page is pushed and vice versa when popping, is it possible to disable any transparency when the page is pushed and popped my code looks like this, i see you have a alpha property but not entirely sure if it achieves what i think it should. What should I set to disable transparency when i push and pop..?

`PageAnimation =
                            new SlidePageAnimation
                            {
                                Subtype = AnimationSubtype
                                        .FromBottom,
                                Duration = AnimationDuration.Medium,
                                Alpha = 0
                            }`

**Comment by AlexandrNikulin** [comment]
@LeoJHarris  Hi Leo! Yes this is possible. If you want disable transparency - set: Alpha = 1.
