### ISSUE TITLE
New Library causes issue in iOS Flow

### ISSUE THREAD

**Issue by fazil1979** [AlexandrNikulin/AnimationNavigationPage#24]
Hello there,

We are facing below issue in our project for iOS, while we upgrade the reference of this component to latest version. Please see details below:

After updating navigation page component in all 3 projects, in ios, major problem we encountered was with carousal pages. In ios, when there are inner pages in one page and if there is some code (for example adding data in views when page appears), the inner page’s OnAppearing method never gets called. This was not the case in previous version. Even calling it using a wrapper method from it’s parent page does not seem to work. More over if there are alert dialogs in page, sometimes more than one alert is shown when tapped on a view which causes a view to appear.

Can you please help us to resolve this issue?

Thanks
Nevil

**Comment by AlexandrNikulin** [comment]
Hello,
Unfortunately this component does not support carousal pages. 
If you want to user carousel features you can use Carousel View.
