### ISSUE TITLE
App crashing when Linking Assemblies

### ISSUE THREAD

**Issue by LeoJHarris** [AlexandrNikulin/AnimationNavigationPage#25]
I have an app using your navigation component, however I cannot have my project set to Link All Assemblies.

When i set my project to Link Assemblies the app is crashing at runtime on the page constructor. I have added SQLite-net;FormsControls.Droid;FormsControls.Base in the skip linking assemblies and added the [Preserve(AllMembers = true)] attribute to all view models and xaml.cs classes as per the xamarin docs to enable linking but still the app is crashing for on the FormsControls.Base

![capture](https://user-images.githubusercontent.com/5468757/30841142-5f20b788-a2d7-11e7-9047-f5ea771f919f.PNG)

Stack trace below:

09-26 16:24:39.328 I/MonoDroid( 4918): UNHANDLED EXCEPTION:
09-26 16:24:39.348 I/MonoDroid( 4918): System.TypeInitializationException: The type initializer for 'TrackitEducationApp.Views.NavigationContentPage' threw an exception. ---> System.TypeInitializationException: The type initializer for 'FormsControls.Base.PageAnimation' threw an exception. ---> System.MissingMethodException: Default constructor not found for type FormsControls.Droid.DroidDevice
09-26 16:24:39.348 I/MonoDroid( 4918):   at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) [0x0007b] in <1ba16eee6b7a4b35b64bdb1a4ded5d62>:0 
09-26 16:24:39.348 I/MonoDroid( 4918):   at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00009] in <1ba16eee6b7a4b35b64bdb1a4ded5d62>:0 
09-26 16:24:39.348 I/MonoDroid( 4918):   at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00027] in <1ba16eee6b7a4b35b64bdb1a4ded5d62>:0 
09-26 16:24:39.348 I/MonoDroid( 4918):   at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x0002c] in <1ba16eee6b7a4b35b64bdb1a4ded5d62>:0 
09-26 16:24:39.348 I/MonoDroid( 4918):   at System.Activator.CreateInstance (System.Type type) [0x00000] in <1ba16eee6b7a4b35b64bdb1a4ded5d62>:0 
09-26 16:24:39.348 I/MonoDroid( 4918):   at Xamarin.Forms.DependencyService.Get[T] (Xamarin.Forms.DependencyFetchTarget fetchTarget) [0x00065] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\DependencyService.cs:35 
09-26 16:24:39.348 I/MonoDroid( 4918):   at FormsControls.Base.PageAnimation..cctor () [0x00000] in <0c881cdde36b4687bbe522f122a38bc0>:0 
09-26 16:24:39.348 I/MonoDroid( 4918):    --- End of inner exception stack trace ---
09-26 16:24:39.348 I/MonoDroid( 4918):   at FormsControls.Base.SlidePageAnimation..ctor () [0x0000b] in <0c881cdde36b4687bbe522f122a38bc0>:0 
09-26 16:24:39.348 I/MonoDroid( 4918):   at TrackitEducationApp.Views.NavigationContentPage..cctor () [0x00000] in C:\TrackitEducation\TrackitEducationApp\TrackitEducationApp\Views\NavigableContentPage.cs:37 
09-26 16:24:39.348 I/MonoDroid( 4918):    --- End of inner exception stack trace ---
09-26 16:24:39.348 I/MonoDroid( 4918):   at TrackitEducationApp.Views.LoginPage..ctor () [0x00000] in C:\TrackitEducation\TrackitEducationApp\TrackitEducationApp\Views\LoginPage.xaml.cs:48 
09-26 16:24:39.348 I/MonoDroid( 4918):   at TrackitEducationApp.App..ctor () [0x00013] in C:\TrackitEducation\TrackitEducationApp\TrackitEducationApp\App.cs:80 
09-26 16:24:39.348 I/MonoDroid( 4918):   at TrackitEducationApp.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x000c5] in C:\TrackitEducation\TrackitEducationApp\TrackitEducationApp.Android\MainActivity.cs:60 
09-26 16:24:39.348 I/MonoDroid( 4918):   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <2c4e5797d5cf4ae5ab98833a1afe1241>:0 
09-26 16:24:39.348 I/MonoDroid( 4918):   at (wrapper dynamic-method) System.Object:9ceead74-05ab-40d4-af96-afcef65236c1 (intptr,intptr,intptr)
09-26 16:24:39.368 D/Mono    ( 4918): Assembly Ref addref HockeySDK.AndroidBindings[0xb83d0ff8] -> System[0xb8668460]: 8
09-26 16:24:39.398 W/art     ( 4918): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable

![capture](https://user-images.githubusercontent.com/5468757/30891411-b8538f70-a38f-11e7-9b7d-548dfe67fd70.PNG)

**Comment by AlexandrNikulin** [comment]
@LeoJHarris  For now Link All options not supported. You should select "Link SDK Assemblies Only".

**Comment by LeoJHarris** [comment]
Okay thanks for the response, do you suppose we might be able to see the ability to Link all sometime in the future with your package?

**Comment by AlexandrNikulin** [comment]
Hi!
Yes, sure. This is possible.

28 сент. 2017 г. 0:59 пользователь "Leonard Harris" <
notifications@github.com> написал:

**Comment by LeoJHarris** [comment]
Just wanted to give a little nudge on this closed issue. It'd be great if we can set the link all and maybe you add this functionality to the pipeline?
