### ISSUE TITLE
Issue in paid version for poping with blank screen on back

### ISSUE THREAD

**Issue by braintechjp** [AlexandrNikulin/AnimationNavigationPage#28]
We are getting blank screen after clicking on back. It is happening on sample too. Please let us know the solution for the same. It is working fine on trial as we are getting popup for trial. In paid version we are getting blank screen.

**Comment by AlexandrNikulin** [comment]
@braintechjp  Find issue. It happened only on  iOS 10 and only with PushAnimation. 
Fixed in ver 1.5.7
