### ISSUE TITLE
Default Animation Left to Right

### ISSUE THREAD

**Issue by russ-enterapp** [AlexandrNikulin/AnimationNavigationPage#3]
On iOS and Android, it seems the default animation for a content page that has not implemented IAnimationPage seems to be opposite what I would expect.  I purchased the control to use on just a few pages, but in order for it to behave correctly, I have to implement the interface on every page.  

I am using FreshMVVM with a custom IFreshNavigationService to inject the AnimationNavigationPage.  I don't think that is causing the issue though as when I explicitly specify the animation I want, they work fine.

**Comment by AlexandrNikulin** [comment]
Hi !  i'm working on new version . Component will be available for some days.
