### ISSUE TITLE
Support tabbedPage ?

### ISSUE THREAD

**Issue by vincentcastagna** [AlexandrNikulin/AnimationNavigationPage#30]
Hello @AlexandrNikulin ,

Bought your package a few months ago. This is really amazing how easy it is to use and how it adds a real "personnality" to an app for go prod. That's the first time I use a tabbedPage, I know XF is not supposed to have a tabbedPage inside a NavigationPage but then how could I manage to get the animation working when pushing the tabbedpage ? 

Thanks !

**Comment by AlexandrNikulin** [comment]
@Umar3x  Hi Umar3, first of all thanks for your comment.

About tabbedPage. For now i have no idea how we can push tabbedPage with animation.

I can offer this
Set tabbedPage as main page in your and 
1) Animate content on tabbedPage by yourself.
2) For pages that should hide tabBar try to use Push Modal.
