### ISSUE TITLE
Buy

### ISSUE THREAD

**Issue by desarrollott** [AlexandrNikulin/AnimationNavigationPage#31]
Hi Alexander, before all thanks so much for to take the time to develop this great component, but.. where i can't buy or download the trial version, i have a little issue in this line:
FormsControls.Droid.Main.Init(this);
in the mainactivity, is a NullReferenceException and i don't know why is this, can you help me with this issue, i have already the lib folder in my project and also i have ready link the dll's.

**Comment by vincentcastagna** [comment]
Hello,

Did you try to clean the solution ? Which xamarin forms version are you using ? Did you init it after XamarinForms initialization ?

**Comment by AlexandrNikulin** [comment]
@desarrollott  Sorry for delay. Please write me on email "nikulin.alexandr.1991@gmail.com"
