### ISSUE TITLE
Component no longer available?

### ISSUE THREAD

**Issue by dackjaniels2001** [AlexandrNikulin/AnimationNavigationPage#32]
Hi,

Can you please tell me if your component will be available in the Xamarin component store again soon?

Thanks,
Steve

**Comment by AlexandrNikulin** [comment]
@dackjaniels2001  Hello, Steve.
Unfortunately  Xamarin component store closed. 
If you need to get/update my component - please write me to email "nikulin.alexandr.1991@gmail.com".

**Comment by vincentcastagna** [comment]
Hi @AlexandrNikulin 

I wanted to check if their was an update and saw on xamarin store it was 1.5.7. Is this the right latest release ? If not, I'll email you to get this. Thanks for your answer.

**Comment by AlexandrNikulin** [comment]
@Umar3x  Latest ver is 1.5.7.
If you want some additional features or private support - email me. Thanks

**Comment by wpanduka** [comment]
I saw your git hub page and the plugin but i cant purchase it because its disabled the purchase option. i am curious ,  i am so interested and i really need this feature in my xamarin applications, can you please guide me, it will be a grate help.

**Comment by AlexandrNikulin** [comment]
@wpanduka  Component now open source. No need to buy

**Comment by LeoJHarris** [comment]
If the project is open source is there a chance we could see this lib made available on nuget for download if it is not there already?

**Comment by AlexandrNikulin** [comment]
@LeoJHarris  Sure, I will do it. Or you can help me with it

**Comment by LeoJHarris** [comment]
I could help out with that. Thanks
