### ISSUE TITLE
nuget and .net standard 2.0

### ISSUE THREAD

**Issue by LeoJHarris** [AlexandrNikulin/AnimationNavigationPage#33]
Hi Alexandr, I am helping you with forming the nuget package for your lib. Your library is using PCL would you like this to be updated to .net standard 2.0

**Comment by AlexandrNikulin** [comment]
Hi Leo! Thanks for you help.
About PCL or .net standard 2.0 for me it does not matter. But as we know .net standard 2.0 is modern way for cross-platform libs.

**Comment by LeoJHarris** [comment]
Hi Alexandr, I have migrated to .net standard 2.0 and also created the nuspec file and nuget package. This is working in a very simple project I created deploying to android, have not checked on iOS as I don't have a mac currently but one will arrive in the coming days that I can do the build and test on iOS and then do a PR

**Comment by AlexandrNikulin** [comment]
@LeoJHarris  Hi Leo!
Great news! Thanks! Please create pull-request to this repo.

**Comment by LeoJHarris** [comment]
Will need to regenerate the nuget package that includes the iOS part

**Comment by AlexandrNikulin** [comment]
Merged
