### ISSUE TITLE
Animation glitching using nuget package iOS - emulator

### ISSUE THREAD

**Issue by LeoJHarris** [AlexandrNikulin/AnimationNavigationPage#36]
Hi Alexandr, I had just tested for iOS and there seems to be a small glitch happening but only for iOS. I have only been able to test on an emulator I don't know how this would render on an actual device for iOS.

See gif examples for iOS and android using the nuget package i generated.
![nav android gif](https://user-images.githubusercontent.com/5468757/38610916-69f36fa8-3dd6-11e8-990b-68cf3ac9fbc2.gif)
![nav ios gif](https://user-images.githubusercontent.com/5468757/38610917-6a240fe6-3dd6-11e8-9812-acbb56bf9dc9.gif)

Can you confirm if you are seeing the same when you deploy to actual iOS device. Am sending the nuget package I generated to you.

**Comment by LeoJHarris** [comment]
Nuget package generated including forms, android and iOS parts

[XForms.Plugin.AnimationNavigationPage.1.0.3.zip](https://github.com/AlexandrNikulin/AnimationNavigationPage/files/1900736/XForms.Plugin.AnimationNavigationPage.1.0.3.zip)

**Comment by LeoJHarris** [comment]
Sorry should see the nuget package now above. One thing to note is it takes ALONG time to install the nuget package which I suppose is just the overall size including dependencies. 

If the above nuget package works well and causes no issues we can potentially go ahead and create an available nuget package :)

**Comment by AlexandrNikulin** [comment]
@LeoJHarris  Thanks! I will check it ASAP and update you.

**Comment by AlexandrNikulin** [comment]
Published on nuget.org
https://www.nuget.org/packages/XForms.Plugin.AnimationNavigationPage
