### ISSUE TITLE
Nuget package has no content

### ISSUE THREAD

**Issue by LeoJHarris** [AlexandrNikulin/AnimationNavigationPage#37]
Hi Alexandr there appears to be an issue with the nuget package, there is no content in it. 

Current nuget package on nuget:

![nocontent](https://user-images.githubusercontent.com/5468757/39452547-b13caf5a-4d26-11e8-8102-8781de44cf46.PNG)

Package I generated locally:

![content](https://user-images.githubusercontent.com/5468757/39452562-b66a85b0-4d26-11e8-8ad9-ee4a8b67f8ca.PNG)

Did you build the project correctly in release?

See my outputted nuget package:

[1.0.3.zip](https://github.com/AlexandrNikulin/AnimationNavigationPage/files/1962303/1.0.3.zip)

**Comment by AlexandrNikulin** [comment]
@LeoJHarris  Thanks, I will check

**Comment by LeoJHarris** [comment]
Hi @AlexandrNikulin do you have any update on this or had the chance to look into this?

**Comment by CarLoOSX** [comment]
Having the same issue !

**Comment by LeoJHarris** [comment]
This really needs to be sorted.

**Comment by AlexandrNikulin** [comment]
@LeoJHarris  Just updated package with your nuget file. Thanks
