### ISSUE TITLE
Issue with Xamarin Forms 3.0+

### ISSUE THREAD

**Issue by LeoJHarris** [AlexandrNikulin/AnimationNavigationPage#39]
Was getting a run-time exception in my project (android) until i removed this package.

System.TypeLoadException: Could not resolve type with token 01000114 (from typeref, class/assembly Xamarin.Forms.Xaml.XamlResourceIdAttribute, Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null)

I cant entirely confirm this is an issue with this plugin but I was having an issue with updating my projects Xamarin Forms to 3.0 but was then able when I removed this package.

We might need to update Xamarin forms in this project and create a new package on nuget.

Anyone else having this issue

**Comment by JoshaMunnik** [comment]
I have the same error. Using the older version from the (no longer existing) component store does work ok though.

I did a quick look-trough in the source and noticed that there is a Controls folder in SourceCode/Lib/FormsControls.Base/ 

This folder contains xaml files using {StaticResource ...} values. My guess is that this folder belongs with the samples? But I'm not sure if this is the cause of the error.

**Comment by AlexandrNikulin** [comment]
For now plugin does not support Xamarin.Forms 3.0
I will implement support when I will have time on it.

**Comment by al3xmeister** [comment]
Hi Alexandr, thanks for your great work. any updates on the above?

**Comment by AlexandrNikulin** [comment]
@al3xmeister  Hi Guys! Sorry, on this week I have not got any time for this issue. I will try to fix it on this weekend
@LeoJHarris @JoshaMunnik @al3xmeister  If you can help with this issue - it will be great (I mean pull-request).

**Comment by LeoJHarris** [comment]
https://github.com/AlexandrNikulin/AnimationNavigationPage/pull/40

Have already done a PR, I have even included the nuget package in the PR

**Comment by AlexandrNikulin** [comment]
@LeoJHarris  Amazing! I will check it tomorrow and merge. Thanks!

**Comment by AlexandrNikulin** [comment]
@LeoJHarris  We have conflicts =( Please solve it.

**Comment by LeoJHarris** [comment]
@AlexandrNikulin Have resolved conflicts

**Comment by AlexandrNikulin** [comment]
Merged and uploaded new nuget. Thank @LeoJHarris
