### ISSUE TITLE
RemovePage crash on Android

### ISSUE THREAD

**Issue by dmitrymov** [AlexandrNikulin/AnimationNavigationPage#4]
I'm using Xamarin.Forms.Platform.Android.FormsAppCompatActivity in my Android project. And when I do:
`navigation.RemovePage(page);//navigation is AnimationNavigationPage`

application crashes in Xamarin.Forms.Platform.Android.NavigationRenderer code.

Xamarin.Forms.Platform.Android.NavigationRenderer code from open source:

```
void RemovePage(Page page)
        {
            IVisualElementRenderer rendererToRemove = Platform.GetRenderer(page);
            PageContainer containerToRemove = rendererToRemove == null ? null : (PageContainer)rendererToRemove.ViewGroup.Parent;

            containerToRemove.RemoveFromParent();

            if (rendererToRemove != null)
            {
                rendererToRemove.ViewGroup.RemoveFromParent();
                rendererToRemove.Dispose();
            }

            containerToRemove?.Dispose();

            Device.StartTimer(TimeSpan.FromMilliseconds(0), () =>
            {
                ((Platform)Element.Platform).UpdateNavigationTitleBar();//Crash here with invalid cast exception
                return false;
            });
        }
```

The problem is that next code trying to cast Element.Platform, which is Android.AppCompat.Platform, to Android.Platform.

((**Platform**)Element.Platform).UpdateNavigationTitleBar();

It would be great if you could fix this and make the AppCompat compability version.

**Comment by AlexandrNikulin** [comment]
AppCompatActivity not supported
