### ISSUE TITLE
Android Animation not rendering

### ISSUE THREAD

**Issue by al3xmeister** [AlexandrNikulin/AnimationNavigationPage#41]
It default to slide from left, no matter what type you select. tested on XF 3.0+ on two projects.

**Comment by al3xmeister** [comment]
@AlexandrNikulin  @LeoJHarris  folks I really like your plugin and want to implement it, but the slider only works from left to right on android on XF 3.0, is there anything in there that can be fixed? please note it works fine on iOS

**Comment by al3xmeister** [comment]
@AlexandrNikulin  I think it would be good practice to let other devs know when implementing the interface, for android to render in XF 3.0 they have to implement the interface on every single content page.

**Comment by AlexandrNikulin** [comment]
@al3xmeister  True, or just use AnimationPage (we have this class in lib).
We have information about it in Readme file.
