### ISSUE TITLE
Getting again TypeLoadException

### ISSUE THREAD

**Issue by felipecds** [AlexandrNikulin/AnimationNavigationPage#42]
I update the Xamarin Forms version to the latest package in nuget, and the exception reported in #39  occurred again.

If it's not possible to you update the version, how can I help?

**Comment by LeoJHarris** [comment]
@felipecds it is possible but its a pretty straight forward solution. Do a fork, update Xamarin.Forms package on solution and then if no issues present PR. I'm assuming if the same issue as https://github.com/AlexandrNikulin/AnimationNavigationPage/issues/39 then we just need to update the XF package.

**Comment by AlexandrNikulin** [comment]
@LeoJHarris @felipecds  Yep, this is the same issue with Xamarin.Forms.
You should use XamarinForms ver 3.0 in your solution or update Xamarin.Forms package to 3.1 for AnimationNavigationPage solution and create pull-request. If you can help with it - please do.

**Comment by AlexandrNikulin** [comment]
@LeoJHarris @felipecds  I agree with Leo. Leo, thank you a lot! If you can update XF package again - please do.

**Comment by felipecds** [comment]
Submitted #43 for revision

**Comment by AlexandrNikulin** [comment]
@felipecds I will test it today and merge if everything is OK. Can you build nuget package with this update ?

**Comment by felipecds** [comment]
I’ve never done yet, but I can try.

**Comment by LeoJHarris** [comment]
@felipecds to generate the nuget package, bump the nuspec file version up. Then do a release build of the Lib. Open up a Command Prompt. Change directory to the directory containing the nuspec file which also has the nuget.exe file then type the command "nuget pack animationnavigationpage.nuspec" this will generate the nuget package.
 
See: https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#creating-the-nuspec-file

**Comment by felipecds** [comment]
@LeoJHarris  Package added!

**Comment by AlexandrNikulin** [comment]
@felipecds  Where ? Please send me this package. I will test it and update on nuget

**Comment by felipecds** [comment]
I added it to my commit, but forgot to attach it here
[XForms.Plugin.AnimationNavigationPage.1.0.5.nupkg.zip](https://github.com/AlexandrNikulin/AnimationNavigationPage/files/2447540/XForms.Plugin.AnimationNavigationPage.1.0.5.nupkg.zip)

**Comment by AlexandrNikulin** [comment]
Great! I will check it and update nuget package

**Comment by AlexandrNikulin** [comment]
I updated Xamarin.Forms to 3.2 and upload new ver for nuget package. @felipecds  @LeoJHarris  thank you and sorry for delay!
