### ISSUE TITLE
Swipe to go back on IOS

### ISSUE THREAD

**Issue by larochelle000** [AlexandrNikulin/AnimationNavigationPage#44]
Hello,
The swipe to go back on IOS plays the default animation and not the one I'm using (rotateAnimation). Do you have a clue on that?

Thanks

**Comment by Satris404** [comment]
Got the same problem here. Can't figure out why it's doing that...

**Comment by AlexandrNikulin** [comment]
@larochelle000  Hello! Are you using for this property "AnimationNavigationPage.EnableInteractivePopGesture" ?

**Comment by larochelle000** [comment]
Hello @AlexandrNikulin, I used `AnimationNavigationPage.EnableInteractivePopGesture = true`. Thanks

**Comment by AlexandrNikulin** [comment]
@larochelle000 Please try any other type of animation. For example Slide or Fade

**Comment by larochelle000** [comment]
@AlexandrNikulin the problem persists even if I change the animation type.

**Comment by AlexandrNikulin** [comment]
@larochelle000  I will fix it when i will have time

**Comment by pmahend1** [comment]
Any update
