### ISSUE TITLE
Alpha property of SlidePageAnimation appears to do nothing

### ISSUE THREAD

**Issue by davehax** [AlexandrNikulin/AnimationNavigationPage#45]
Hello, I'm hoping to gain some clarity regarding the purpose of the "Alpha" property of the SlidePageAnimation class.

From my testing, it appears to serve no purpose.

I'm using Xamarin.Forms 3.2.0.817, and XForms.Plugin.AnimationNavigationPage 1.0.5.
My testing has been conducted on the Android platform.

**Comment by AlexandrNikulin** [comment]
@davehax  Hello! Yes, you are right. For now it's do nothing. I will remove it
