### ISSUE TITLE
Problem with Xamarin Forms v3.3.0

### ISSUE THREAD

**Issue by JoshaMunnik** [AlexandrNikulin/AnimationNavigationPage#46]
I've come across a problem when trying to use the nuget package with v3.3.0.xxxxx. 

To reproduce:
1. Create new Xamarin mobile project in vs studio, check if it uses Xamarin Forms v3.3.0.912540 or v3.3.0.967583
2. Add 'FontAttributes="Bold"' to the generated label in MainPage.xaml
3. Optional run (Debug version) to see that all is working
4. Install AnimationNavigationPage nupackage with nuget manager
5. Run application (Debug version)

With 5. I get the following exception: "System.TypeLoadException: Could not resolve type with token 01000018 (from typeref, class/assembly Xamarin.Forms.FontAttributesConverter, Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null) occurred"

Trying to build a Release version of the test app will give an "LinkAssemblies" task failure.

When reverting back to the latest Xamarin Forms v3.2 the TypeLoadException does not occur.

**Comment by AlexandrNikulin** [comment]
@JoshaMunnik Hi! Thanks for inform. I will update nuget package on this week. For now you can use this lib with Xamarin Fomrs v3.2

**Comment by StanBM** [comment]
Hello @AlexandrNikulin, please update the package for Xamarin Forms v3.4 also :)

**Comment by AlexandrNikulin** [comment]
Update nuget package (ver 1.0.6) for Xamarin.Forms 3.4
