### ISSUE TITLE
OnAnimation(Started|Finished) not called for empty animation

### ISSUE THREAD

**Issue by kimbirkelund** [AlexandrNikulin/AnimationNavigationPage#47]
Hi

When using the EmptyPageAnimation it appears that on iOS the OnAnimation(Started|Finished) methods aren't called. It also appears to be the case if Duration is Zero.

Is this correct and if so what is the rational behind this? 

I'd have a page where I'd like to have a slide animation for first time users and no animation for returning users (as I have a custom in-page animation for those users). Currently I'm using the OnAnimation(Started|Finished) methods for this, which isn't working. 

I can work around this using `new PageAnimation { Type = Fade, Duration = Short }`, but it seems unnecessary and makes the code less intuitive and maintainable.

**Comment by AlexandrNikulin** [comment]
@kimbirkelund  Hi!

Actually EmptyPageAnimation or if Duration is Zero is not a animation.  This lack of animation and true in this case OnAnimation(Started|Finished)  aren't called.

**Comment by AlexandrNikulin** [comment]
@kimbirkelund  In your case you can use methods OnAppearing for returning users.
