### ISSUE TITLE
Android build issues

### ISSUE THREAD

**Issue by bazg177** [AlexandrNikulin/AnimationNavigationPage#48]
Hi,

I am receiving the following build errors when integrating the package:

<img width="805" alt="2019-01-19 12_26_09-jobzappa - microsoft visual studio" src="https://user-images.githubusercontent.com/46842148/51426647-7ec7e100-1be5-11e9-8a3f-a1414110d41d.png">

Targeting Android API 28

Any ideas?

**Comment by LeoJHarris** [comment]
@bazg777 Could be due to a copy of the Xamarin libraries inside your android/ios platform libs which maybe causing conflicts with the nuget references already in the project.

I think we need to cleanup the project and not pull all the Xamarin Libs inside the plugin but add as a dependency.

**Comment by LeoJHarris** [comment]
@bazg777 sorry try simply updating your android support libs.

**Comment by kimbirkelund** [comment]
I have this exact issue as well. On latest support libs (28.0.0.1).

**Comment by AlexandrNikulin** [comment]
Fixed in ver 1.0.7
