### ISSUE TITLE
The documention is very poor

### ISSUE THREAD

**Issue by jonathanroze** [AlexandrNikulin/AnimationNavigationPage#5]
Hey, 

I have buy your plugin for Xamarin but your documentation is very poor... I have add references, edit my delegate, edit my app.css but after ? You doesn't give more informations... I want to you C# to build my view.

**Comment by AlexandrNikulin** [comment]
@Clowning Hey Jonathan,
True documentation very poor. But for now i have not time on it.
If you have some questions - ask me. I will happy to help.
