### ISSUE TITLE
FlipPageAnimation doesn't work on Android

### ISSUE THREAD

**Issue by Pir-2** [AlexandrNikulin/AnimationNavigationPage#53]
Hello,

FlipPageAnimation seems not working on Android. I can't test on an Iphone right now.
The others Animation works perfectly ! 

My code for the FlipPageAnimation on my destination page (Page1.xaml) :
`        
public IPageAnimation PageAnimation { get; } = new FlipPageAnimation { Duration = AnimationDuration.Long, Subtype = AnimationSubtype.FromRight };
`

And the push from my Main Page :
`        
private async void GoToNextPage(object sender, EventArgs e)
{
     await Navigation.PushAsync(new Page1());
}`

Any idea ? Thanks !

**Comment by AlexandrNikulin** [comment]
yep, unfortunately  FlipPageAnimation does not work with FormsAppCompatActivity (only with FormsApplicationActivity). For now I don't know how to add this support
