### ISSUE TITLE
Navigation Bar is not visible

### ISSUE THREAD

**Issue by GravityRabbit** [AlexandrNikulin/AnimationNavigationPage#6]
With latest version of AnimationNavigationPage, and using Xamarin Forms 2.3.0.46-pre3, the Navigation Bar will not display. I'm not sure if it works in earlier versions of XF. We're committed to use this pre release as we have been advised by Xamarin that by the time we release our app, that will be the stable version. I've tried calling SetNavigationBarVisible to true, that didn't help.

**Comment by GravityRabbit** [comment]
Another note: I created a simple app like you have in your example, using the latest stable xamarin forms (not pre release), and still cannot get the Navigation bar to show up. Any help would be appreciated.

**Comment by GravityRabbit** [comment]
I need to get this resolved or I can't use your plugin. I believe it has to do with Xamarin Forms using the Toolbar rather than the ActionBar, but I'm not positive.

**Comment by AlexandrNikulin** [comment]
AppCompatActivity not supported
