### ISSUE TITLE
Label custom renderers stop working

### ISSUE THREAD

**Issue by gusmanb** [AlexandrNikulin/AnimationNavigationPage#7]
Hi.

We are testing the component, it's great, but when we add it to our project our custom label renderers stop working on Android.

Any ideas?

It's the only thing which stops us from buying it...

**Comment by AlexandrNikulin** [comment]
True, in my component i use custom renderer for standard label. 
Fixed, but for now control not available.

**Comment by gusmanb** [comment]
Hi @AlexandrNikulin.

We have already bought the component, would you be so kind to notify us when the NuGet package gets updated?

Thanks.

**Comment by AlexandrNikulin** [comment]
Hi @gusmanb 
I spend a lot of time on this control, and it's price very little. So i'm stop working on public package and use it only in my private projects. 
If you want support and updates for this package - we can discuss it in private chat.

**Comment by gusmanb** [comment]
Hi @AlexandrNikulin 

Ok, I understand the situation.

How can I contact you? We may be interested on private support and updates.

**Comment by AlexandrNikulin** [comment]
Hi @gusmanb 
You can contact me by email: nikulin.alexandr.1991@gmail.com
