### ISSUE TITLE
NullReferenceException on PushAsync after updating to Xamarin.Forms 2.3.1.114

### ISSUE THREAD

**Issue by Pimsch** [AlexandrNikulin/AnimationNavigationPage#8]
After updating to newest Xamarin.Forms version our app crashes everytime on PushAsync while using your NavigationPage. I attached a Stacktrace that might help to identify the issue.

[AnimationNavigationPage.txt](https://github.com/AlexandrNikulin/AnimationNavigationPage/files/422052/AnimationNavigationPage.txt)

**Comment by AlexandrNikulin** [comment]
Fixed. But control not avalible for now
